---
- name: Install Cisco IOS collection
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Ensure cisco.ios collection is installed
      ansible.builtin.ansible_galaxy:
        name: cisco.ios
        type: collection
        state: present

- name: Create VLAN 128 on switches
  hosts: switches
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_user: "{{ semaphore_user }}"
    ansible_password: "{{ semaphore_password }}"
    vlan_id: 128
    vlan_name: VLAN_128
  tasks:
    - name: Ensure VLAN 128 is present
      cisco.ios.ios_vlan:
        vlan_id: "{{ vlan_id }}"
        name: "{{ vlan_name }}"
        state: present
