---
- name: Install Cisco IOS collection
  hosts: localhost
  gather_facts: no
  roles:
    - install_cisco_ios_collection

- name: Create VLAN 128 on switches
  hosts: switches
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_user: "{{ semaphore_user }}"
    ansible_password: "{{ semaphore_password }}"
    vlan_id: 128
    vlan_name: VLAN_128
  roles:
    - create_vlan
