---
- name: Install Cisco IOS collection
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Install cisco.ios collection
      ansible.builtin.command: ansible-galaxy collection install cisco.ios --force
      args:
        creates: "/root/.ansible/collections/ansible_collections/cisco/ios"

- name: Create VLAN 128 on switches
  hosts: switches
  gather_facts: no
  connection: network_cli
  collections:
    - cisco.ios
  vars:
    ansible_network_os: ios
    ansible_user: "{{ semaphore_user }}"
    ansible_password: "{{ semaphore_password }}"
    vlan_id: 128
    vlan_name: VLAN_128
  tasks:
    - name: Ensure VLAN {{ vlan_id }} is present
      ios_vlan:
        vlan_id: "{{ vlan_id }}"
        name: "{{ vlan_name }}"
        state: present
